build-dependencies: []
dependencies: [libmcrypt-dev,libmhash-dev]
library: mcrypt
install_type: source
variables:
  version:
    - 2.5.8
source:
  - "ftp://mcrypt.hellug.gr/pub/crypto/mcrypt/attic/old/mcrypt-2.5.8.tar.gz"
