install_type: remote
library: 'proftpd'
public_keys: []
source:
  - "http://ftp.riken.jp/net/ProFTPD/historic/source/proftpd-1.3.2c.tar.bz2"
constants:
  builddeps: ['bzip2', 'rsyslog']
variables:
  version:
    - '1.3.2c'
  cflags:
    - ''
    - '-fsanitize=address'
    - '-fsanitize=safe-stack'
