public_keys: []
notes: |
  Demonstration of ProFTPD Remote exploit, and the effectiveness of 
  Clang's Address Sanitizer.
files:
  source:
    - "http://ftp.riken.jp/net/ProFTPD/historic/source/proftpd-1.3.2c.tar.bz2"
constants:
  builddeps: ['bzip2','rsyslog']
  install_type: source
  library: 'proftpd'
  provider: docker
variables:
  version:
    - '1.3.2c'
  cflags:
    - ''
    - '-fsanitize=address'
