constants:
  build_dependencies: []
  install_type: debian
  library: linux-image
  provider: vagrant
notes: |
  Demonstration of perf_event_open exploit using Ubuntu Raring 64, Kernel 3.8.8
public_keys: []
files: 
  packages/linux-image-3.8.8:
    - "http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.8.8-raring/linux-headers-3.8.8-030808-generic_3.8.8-030808.201304170248_amd64.deb"
    - "http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.8.8-raring/linux-headers-3.8.8-030808_3.8.8-030808.201304170248_all.deb"
    - "http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.8.8-raring/linux-image-3.8.8-030808-generic_3.8.8-030808.201304170248_amd64.deb"
variables:
  version:
    - '3.8.8'
