build-dependencies: []
library: bash
constants:
  dependencies: []
  version: 4.3
  patch: 0
  cve: 6271
install_type: 'source'
public_keys:
 - "64EA74AB"
source:
 - "http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz"
 - "http://ftp.gnu.org/gnu/bash/bash-4.3-patches/bash43-{001,002,003,004,005,006,007,008,009,010,011,012,013,014,015,016,017,018,019,020,021,022,023,024,025,026,027,028,029,030,031,032,033,034,035,036,037,038,039}"
notes: |
    Move patch files patch folder in target context

    mkdir containers/target/patches && mv source/bash43* containers/target/patches/
