constants:
  build_dependencies: []
  install_type: remote
  library: linux-image
  provider: vagrant
notes: |
  Demonstrates OverlayFS vulnerability in kernel 3.16 using a stock
  Ubuntu Utopic 64 image. 
public_keys: []
files: {}
variables:
  version:
    - '3.16'
