install_type: source
library: samba
notes: ''
public_keys: []
source: 
  - "https://download.samba.org/pub/samba/stable/samba-3.5.11.tar.gz"
constants:
  dependencies: []
  builddependencies: 
    - vim
    - bzip2
    - libc6-dev-i386
  version: 3.5.11
