build-dependencies: [g++,libpcre3,libpcre3-dev,libncurses5-dev]
dependencies: []
library: vfu
install_type: source
variables:
  version:
    - "4.10"
source:
  - "http://cade.datamax.bg/vfu/previous_releases/vfu-4.10.tar.gz"
public_keys:
  - "EAB5 92CC D845 804B F59E  5288 9019 B8B4 6F35 B214"
