build-dependencies: []
dependencies: []
library: libjpeg
install_type: source
constants:
  cflag: ''
variables:
  version:
    - '6b'
    - '7'
    - '8'
    - '8a'
    - '8b'
    - '8c'
    - '8d'
    - '9'
    - '9a'
source:
  - http://www.ijg.org/files/jpegsrc.v{6b,7,8,8a,8b,8c,8d,9,9a}.tar.gz
notes: |
    The upstream does not provide any file verification.

    Files are improperly named, for each file, 
    please rename to libjpeg-<version>.tar.gz. 
