build-dependencies: []
dependencies: []
library: libjpeg
install_type: source
variables:
  version:
    - 6b
    - 9
  cflag:
    - ""
    - "-fsanitize=memory"
source:
  - http://www.ijg.org/files/jpegsrc.v{6b,9}.tar.gz
notes: |
    The upstream does not provide any file verification.

    Files are improperly named, for each file, 
    please rename to libjpeg-<version>.tar.gz. 
