constants:
  build_dependencies: []
  install_type: source
  library: libjpeg
  provider: docker
public_keys: []
files:
  source: 
    - http://www.ijg.org/files/jpegsrc.v{6b,7,8,9}.tar.gz
variables:
  cflag:
    - ''
    - '-fsanitize=memory'
  version:
    - '6b'
    - '7'
    - '8'
    - '9'
notes: |
    This project demonstrates a memory leak in libjpec (CVE-2013-6629),
        and shows how it can be patched using Clang's Memory Sanitizer flag.

    The upstream does not provide any file verification. 

    Files are improperly named, for each file please rename to
    libjpeg-<version>.tar.gz
