constants:
  build_dependencies: []
  install_type: debian
  library: linux-image
  provider: xshopvb
notes: |
        Test for vulnerability to CVE-2010-3904 in kernel 2.6.32
public_keys: []
source: []
files:
  packages/linux-image-2.6.32:
    - "http://kernel.ubuntu.com/~kernel-ppa/mainline/v2.6.32-lucid/linux-headers-2.6.32-020632-generic_2.6.32-020632.201502252235_amd64.deb"
    - "http://kernel.ubuntu.com/~kernel-ppa/mainline/v2.6.32-lucid/linux-headers-2.6.32-020632_2.6.32-020632.201502252235_all.deb"
    - "http://kernel.ubuntu.com/~kernel-ppa/mainline/v2.6.32-lucid/linux-image-2.6.32-020632-generic_2.6.32-020632.201502252235_amd64.deb"
variables:
  version:
    - '2.6.32'
