build-dependencies: []
dependencies: []
install_type: source
library: hello
notes: 'Example Project Used for Testing Compilation'
public_keys: 
  - "FDE9B739"
source: 
  - "http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz"
constants:
  version: "2.10"
