attacker:
  build: attacker/
  links:
    - target 
  command: /bin/bash -c "while true; do sleep .1; done"
  environment:
    CONTAINER_NAME: attacker
target:
  build: target/
  environment:
    CONTAINER_NAME: target
  command: /bin/bash -c "while true; do sleep .1; done"
