constants:
  builddeps: [gawk, autoconf]
dependencies: []
library: glibc
install_type: source
variables:
  version:
    - 2.17
    - 2.18
source:
  - "http://ftp.gnu.org/gnu/glibc/glibc-{2.17,2.18}.tar.gz"
public_keys:
  - "6C2A4AFF"
  - "82764ED5"

