constants:
  builddeps: [gawk, autoconf]
  library: glibc
  install_type: source
  provider: docker
variables:
  version:
    - 2.17
    - 2.18
files:
  source:
    - "http://ftp.gnu.org/gnu/glibc/glibc-{2.17,2.18}.tar.gz"
public_keys:
  - "6C2A4AFF"
  - "82764ED5"

