build-dependencies: [vim, tar]
dependencies: []
install_type: remote
library: ROP-Simple
notes: ''
public_keys: []
source: []
variables:
  cflags:
#    - ""
#    - "-fsanitize=address"
    - "-fsanitize=cfi -flto"
