constants:
  builddeps: ['vim', 'gcc-multilib', 'python-pip', 'python-dev', 'libswitch-perl', 'gdb']
  dependencies: []
install_type: source
library: BOF
public_keys: []
source: []
variables:
  version: ['1']
notes: |
  The xshop test is in the test.log
  Please find BinCFi in test.log
  Then you can find addresses which can be jumped by overflow
