constants:
  build_dependencies: []
  install_type: remote
  library: linux-image
  provider: vagrant
notes: |
  Demonstration of Mempodipper privilege escalation using a Oneiric image 
  with Kernel 3.0.0
public_keys: []
source: []
files: {}
variables:
  version:
    - '3.0.0'
