constants:
  build_dependencies: []
  install_type: source
  library: libjpeg
  provider: docker
public_keys: []
source: 
  - http://www.ijg.org/files/jpegsrc.v{6b,7,8,9}.tar.gz
variables:
  version:
    - '6b'
    - '7'
    - '8'
    - '9'
notes: |
    The upstream does not provide any file verification. 

    Files are improperly named, for each file please rename to
    libjpeg-<version>.tar.gz
