build-dependencies: []
dependencies: []
library: tiff
install_type: source
variables:
  version:
    - 3.8.2
source:
  - "http://download.osgeo.org/libtiff/old/tiff-3.8.2.tar.gz"
notes: | 
    The upstream does not provide file verification.
